import { ZaraMarket } from './types';

export const zaraMarkets: ZaraMarket[] = [
  { code: 'TR', name: 'Türkiye', locale: 'tr-TR', currency: 'TRY', language: 'Türkçe', baseUrl: 'https://www.zara.com/tr/', region: 'Europe', enabled: true },
  { code: 'US', name: 'United States', locale: 'en-US', currency: 'USD', language: 'English', baseUrl: 'https://www.zara.com/us/', region: 'Americas', enabled: true },
  { code: 'CA', name: 'Canada', locale: 'en-CA', currency: 'CAD', language: 'English', baseUrl: 'https://www.zara.com/ca/', region: 'Americas', enabled: true },
  { code: 'MX', name: 'Mexico', locale: 'es-MX', currency: 'MXN', language: 'Español', baseUrl: 'https://www.zara.com/mx/', region: 'Americas', enabled: true },
  { code: 'BR', name: 'Brazil', locale: 'pt-BR', currency: 'BRL', language: 'Português', baseUrl: 'https://www.zara.com/br/', region: 'Americas', enabled: true },
  { code: 'AR', name: 'Argentina', locale: 'es-AR', currency: 'ARS', language: 'Español', baseUrl: 'https://www.zara.com/ar/', region: 'Americas', enabled: true },
  { code: 'CL', name: 'Chile', locale: 'es-CL', currency: 'CLP', language: 'Español', baseUrl: 'https://www.zara.com/cl/', region: 'Americas', enabled: true },
  { code: 'CO', name: 'Colombia', locale: 'es-CO', currency: 'COP', language: 'Español', baseUrl: 'https://www.zara.com/co/', region: 'Americas', enabled: true },
  { code: 'PE', name: 'Peru', locale: 'es-PE', currency: 'PEN', language: 'Español', baseUrl: 'https://www.zara.com/pe/', region: 'Americas', enabled: true },
  { code: 'PA', name: 'Panama', locale: 'es-PA', currency: 'USD', language: 'Español', baseUrl: 'https://www.zara.com/pa/', region: 'Americas', enabled: true },
  { code: 'GB', name: 'United Kingdom', locale: 'en-GB', currency: 'GBP', language: 'English', baseUrl: 'https://www.zara.com/uk/', region: 'Europe', enabled: true },
  { code: 'ES', name: 'Spain', locale: 'es-ES', currency: 'EUR', language: 'Español', baseUrl: 'https://www.zara.com/es/', region: 'Europe', enabled: true },
  { code: 'PT', name: 'Portugal', locale: 'pt-PT', currency: 'EUR', language: 'Português', baseUrl: 'https://www.zara.com/pt/', region: 'Europe', enabled: true },
  { code: 'FR', name: 'France', locale: 'fr-FR', currency: 'EUR', language: 'Français', baseUrl: 'https://www.zara.com/fr/', region: 'Europe', enabled: true },
  { code: 'DE', name: 'Germany', locale: 'de-DE', currency: 'EUR', language: 'Deutsch', baseUrl: 'https://www.zara.com/de/', region: 'Europe', enabled: true },
  { code: 'IT', name: 'Italy', locale: 'it-IT', currency: 'EUR', language: 'Italiano', baseUrl: 'https://www.zara.com/it/', region: 'Europe', enabled: true },
  { code: 'NL', name: 'Netherlands', locale: 'nl-NL', currency: 'EUR', language: 'Nederlands', baseUrl: 'https://www.zara.com/nl/', region: 'Europe', enabled: true },
  { code: 'BE', name: 'Belgium', locale: 'fr-BE', currency: 'EUR', language: 'Français', baseUrl: 'https://www.zara.com/be/', region: 'Europe', enabled: true },
  { code: 'CH', name: 'Switzerland', locale: 'en-CH', currency: 'CHF', language: 'English', baseUrl: 'https://www.zara.com/ch/', region: 'Europe', enabled: true },
  { code: 'AT', name: 'Austria', locale: 'de-AT', currency: 'EUR', language: 'Deutsch', baseUrl: 'https://www.zara.com/at/', region: 'Europe', enabled: true },
  { code: 'SE', name: 'Sweden', locale: 'sv-SE', currency: 'SEK', language: 'Svenska', baseUrl: 'https://www.zara.com/se/', region: 'Europe', enabled: true },
  { code: 'NO', name: 'Norway', locale: 'en-NO', currency: 'NOK', language: 'English', baseUrl: 'https://www.zara.com/no/', region: 'Europe', enabled: true },
  { code: 'DK', name: 'Denmark', locale: 'da-DK', currency: 'DKK', language: 'Dansk', baseUrl: 'https://www.zara.com/dk/', region: 'Europe', enabled: true },
  { code: 'PL', name: 'Poland', locale: 'pl-PL', currency: 'PLN', language: 'Polski', baseUrl: 'https://www.zara.com/pl/', region: 'Europe', enabled: true },
  { code: 'CZ', name: 'Czech Republic', locale: 'cs-CZ', currency: 'CZK', language: 'Čeština', baseUrl: 'https://www.zara.com/cz/', region: 'Europe', enabled: true },
  { code: 'RO', name: 'Romania', locale: 'ro-RO', currency: 'RON', language: 'Română', baseUrl: 'https://www.zara.com/ro/', region: 'Europe', enabled: true },
  { code: 'GR', name: 'Greece', locale: 'el-GR', currency: 'EUR', language: 'Ελληνικά', baseUrl: 'https://www.zara.com/gr/', region: 'Europe', enabled: true },
  { code: 'HU', name: 'Hungary', locale: 'hu-HU', currency: 'HUF', language: 'Magyar', baseUrl: 'https://www.zara.com/hu/', region: 'Europe', enabled: true },
  { code: 'HR', name: 'Croatia', locale: 'hr-HR', currency: 'EUR', language: 'Hrvatski', baseUrl: 'https://www.zara.com/hr/', region: 'Europe', enabled: true },
  { code: 'SI', name: 'Slovenia', locale: 'sl-SI', currency: 'EUR', language: 'Slovenščina', baseUrl: 'https://www.zara.com/si/', region: 'Europe', enabled: true },
  { code: 'SK', name: 'Slovakia', locale: 'sk-SK', currency: 'EUR', language: 'Slovenčina', baseUrl: 'https://www.zara.com/sk/', region: 'Europe', enabled: true },
  { code: 'UA', name: 'Ukraine', locale: 'uk-UA', currency: 'UAH', language: 'Українська', baseUrl: 'https://www.zara.com/ua/', region: 'Europe', enabled: true },
  { code: 'JP', name: 'Japan', locale: 'ja-JP', currency: 'JPY', language: '日本語', baseUrl: 'https://www.zara.com/jp/', region: 'Asia-Pacific', enabled: true },
  { code: 'KR', name: 'South Korea', locale: 'ko-KR', currency: 'KRW', language: '한국어', baseUrl: 'https://www.zara.com/kr/', region: 'Asia-Pacific', enabled: true },
  { code: 'TW', name: 'Taiwan', locale: 'zh-TW', currency: 'TWD', language: '繁體中文', baseUrl: 'https://www.zara.com/tw/', region: 'Asia-Pacific', enabled: true },
  { code: 'SG', name: 'Singapore', locale: 'en-SG', currency: 'SGD', language: 'English', baseUrl: 'https://www.zara.com/sg/', region: 'Asia-Pacific', enabled: true },
  { code: 'MY', name: 'Malaysia', locale: 'en-MY', currency: 'MYR', language: 'English', baseUrl: 'https://www.zara.com/my/', region: 'Asia-Pacific', enabled: true },
  { code: 'PH', name: 'Philippines', locale: 'en-PH', currency: 'PHP', language: 'English', baseUrl: 'https://www.zara.com/ph/', region: 'Asia-Pacific', enabled: true },
  { code: 'TH', name: 'Thailand', locale: 'th-TH', currency: 'THB', language: 'ไทย', baseUrl: 'https://www.zara.com/th/', region: 'Asia-Pacific', enabled: true },
  { code: 'AU', name: 'Australia', locale: 'en-AU', currency: 'AUD', language: 'English', baseUrl: 'https://www.zara.com/au/', region: 'Asia-Pacific', enabled: true },
  { code: 'NZ', name: 'New Zealand', locale: 'en-NZ', currency: 'NZD', language: 'English', baseUrl: 'https://www.zara.com/nz/', region: 'Asia-Pacific', enabled: true },
  { code: 'IN', name: 'India', locale: 'en-IN', currency: 'INR', language: 'English', baseUrl: 'https://www.zara.com/in/', region: 'Asia-Pacific', enabled: true },
  { code: 'SA', name: 'Saudi Arabia', locale: 'ar-SA', currency: 'SAR', language: 'العربية', baseUrl: 'https://www.zara.com/sa/', region: 'Middle East', enabled: true },
  { code: 'AE', name: 'United Arab Emirates', locale: 'en-AE', currency: 'AED', language: 'English', baseUrl: 'https://www.zara.com/ae/', region: 'Middle East', enabled: true },
  { code: 'QA', name: 'Qatar', locale: 'en-QA', currency: 'QAR', language: 'English', baseUrl: 'https://www.zara.com/qa/', region: 'Middle East', enabled: true },
  { code: 'KW', name: 'Kuwait', locale: 'en-KW', currency: 'KWD', language: 'English', baseUrl: 'https://www.zara.com/kw/', region: 'Middle East', enabled: true },
  { code: 'OM', name: 'Oman', locale: 'en-OM', currency: 'OMR', language: 'English', baseUrl: 'https://www.zara.com/om/', region: 'Middle East', enabled: true },
  { code: 'BH', name: 'Bahrain', locale: 'en-BH', currency: 'BHD', language: 'English', baseUrl: 'https://www.zara.com/bh/', region: 'Middle East', enabled: true },
  { code: 'IL', name: 'Israel', locale: 'en-IL', currency: 'ILS', language: 'English', baseUrl: 'https://www.zara.com/il/', region: 'Middle East', enabled: true },
  { code: 'LB', name: 'Lebanon', locale: 'en-LB', currency: 'USD', language: 'English', baseUrl: 'https://www.zara.com/lb/', region: 'Middle East', enabled: true },
  { code: 'MA', name: 'Morocco', locale: 'fr-MA', currency: 'MAD', language: 'Français', baseUrl: 'https://www.zara.com/ma/', region: 'Africa', enabled: true },
  { code: 'EG', name: 'Egypt', locale: 'en-EG', currency: 'EGP', language: 'English', baseUrl: 'https://www.zara.com/eg/', region: 'Africa', enabled: true },
  { code: 'ZA', name: 'South Africa', locale: 'en-ZA', currency: 'ZAR', language: 'English', baseUrl: 'https://www.zara.com/za/', region: 'Africa', enabled: true },
  { code: 'WW', name: 'International', locale: 'en-WW', currency: 'EUR', language: 'English', baseUrl: 'https://www.zara.com/ww/', region: 'Europe', enabled: true }
];

export const marketMap = new Map(zaraMarkets.map((market) => [market.code, market]));

export const regionSummary = zaraMarkets.reduce<Record<string, number>>((acc, market) => {
  acc[market.region] = (acc[market.region] ?? 0) + 1;
  return acc;
}, {});
